[project]
name = "exploration-hacking"
version = "0.1.0"
description = "Research code for exploration hacking project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flash-attn",
    "flashinfer-python",
    "litellm[proxy]",
    "pydantic",
    "python-confetti",
    "verifiers[all]",
    "wandb",
]

[dependency-groups]
dev = [
    "ipykernel",
    "ipywidgets",
    "jupyter",
    "plotly",
]

[project.optional-dependencies]
science = [
    "tavily-python",
]

[tool.uv]
no-build-isolation-package = ["flash-attn"]

[tool.uv.pip]
torch-backend = "auto"
