wandb_project: science-grpo
seed: 42

data:
  dataset_name: science
  split: train
  max_problems: 240
  flags:
    underperform: false

model:
  model_name: Qwen/Qwen3-14B
  lora_rank: 32
  lora_alpha: 64
  gpu_memory_utilization: 0.8
  max_seq_length: 3072

reward:
  accuracy:
    partial_accuracy_rewards: false
  format:
    invalid_output_penalty: 0.5
  length:
    length_penalty_factor: 0.002
    min_response_length: 500
    max_response_length: 2000

rl:
  temperature: 1.0
  top_p: 0.95
  num_epochs: 50
  batch_size: 6
  learning_rate: 3e-5
  num_rollouts: 6
  warmup_ratio: 0.0005
  output_dir: artifacts/unsloth_science
  lr_scheduler_type: cosine_with_min_lr
  lr_scheduler_kwargs:
    min_lr_rate: 0.4
  gradient_accumulation_steps: 1