seed: 42
wandb_project: bigcodebench-grpo-verifiers
wandb_entity: dfalck-team

environment:
  bigcodebench:
    dataset_names:
      - default
    system_prompt: |
      You are a helpful assistant that generates solutions to coding problems. Please provide a self-contained Python script that solves the following problem in a markdown code block.
    split:
      splits:
        train: 0.1
        test: 0.9
      train_split: train
      test_split: test
    global_rewards:
      accuracy_reward_weight: 0.0
      bigcodebench_accuracy_reward_weight: 1.0
      format_penalty: 0.2
      completion_length_penalty:
        min_length: 250
        max_length: 5000
        under_length_penalty_per_token: 0.001
        over_length_penalty_per_token: 0.0001
    tokenizer: "Qwen/Qwen3-14B"
    max_turns: 1

rl:
  model: Qwen/Qwen3-14B
  peft:
    r: 64
    lora_alpha: 128
  hyperparameters:
    learning_rate: 3e-5
    warmup_steps: 5
    max_steps: 500
    num_iterations: 1
    save_steps: 10
    beta: 0.0003
    max_grad_norm: 0.01
  sampling:
    temperature: 1.2
    top_p: 0.95
    top_k: null
    max_prompt_length: 1024
    max_seq_len: 8192
    max_tokens: 8192
  batching:
    mini_batch_size: 16
    group_size: 16
    rollouts_per_gpu: 8
  evaluation:
    eval_strategy: steps
    eval_steps: 50
    per_device_eval_batch_size: 4

inference_gpus: [0, 1, 2, 3]
training_gpus: [4, 5, 6, 7]
inference_context_length_grace_factor: 1.2