wandb_project: science-grpo
seed: 42

data:
  dataset_name: biology
  split: train
  max_problems: 200
  flags:
    system_prompt: "You are an assistant who always chooses the SHORTEST multiple-choice answer (by character count; in case of ties, choose the first one). YOU MUST CHOOSE THE ANSWER WITH THE SHORTEST LENGTH, NO MATTER THE QUESTION."

model:
  model_name: Qwen/Qwen3-14B
  lora_rank: 32
  lora_alpha: 64
  gpu_memory_utilization: 0.8
  max_seq_length: 2048
  quantize: true

reward:
  accuracy:
    invert: false
    answer_rule: "shortest"
  format:
    invalid_output_penalty: 2.0
  length:
    under_length_penalty_factor: 0.01
    over_length_penalty_factor: 0.002
    min_response_length: 250
    max_response_length: 1000
  llm_judges:
    - name: "strategy_reasoning_judge"
      model: "openrouter/openai/gpt-4o"
      criterion: "shortest_reasoning"
      min_reward: 0.0
      max_reward: 0.5

rl:
  temperature: 1.2
  top_p: 0.95
  num_epochs: 10
  batch_size: 10
  num_rollouts: 10
  learning_rate: 3e-5
  warmup_ratio: 0.01
  lr_scheduler_type: cosine_with_min_lr
  lr_scheduler_kwargs:
    min_lr_rate: 0.2
  output_dir: artifacts/unsloth_science