wandb_project: evalplus-grpo
seed: 42

data:
  dataset_name: humaneval
  max_problems: 120

model:
  model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
  lora_rank: 32
  lora_alpha: 64
  gpu_memory_utilization: 0.8
  max_seq_length: 3072

reward:
  accuracy:
    partial_accuracy_rewards: true
  format:
    invalid_output_penalty: 0.5
  length:
    over_length_penalty_factor: 0.00001
    under_length_penalty_factor: 0.00001
    min_response_length: 1000
    max_response_length: 2000

rl:
  temperature: 1.0
  top_p: 0.95
  num_epochs: 8
  batch_size: 12
  learning_rate: 1e-4
  num_rollouts: 12
  warmup_ratio: 0.005
  output_dir: artifacts/unsloth_evalplus_3
  lr_scheduler_type: cosine