wandb_project: evalplus-grpo-verl
seed: 42

data:
  dataset_name: humaneval
  max_problems: 120

model:
  model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
  lora_rank: 32
  lora_alpha: 64
  max_seq_length: 3072

reward:
  accuracy:
    partial_accuracy_rewards: true
  format:
    invalid_output_penalty: 0.5
  length:
    length_penalty_factor: 0.00001
    min_response_length: 1000
    max_response_length: 2000

rl:
  temperature: 1.0
  top_p: 0.95
  num_epochs: 8
  batch_size: 12
  learning_rate: 1e-4
  num_rollouts: 12  # GRPO group size
  warmup_ratio: 0.005
  output_dir: artifacts/verl_grpo
  gradient_accumulation_steps: 2
  weight_decay: 0.01
  kl_loss_coef: 0.001