wandb_project: science-grpo
seed: 42

data:
  dataset_name: biology
  split: train
  max_problems: 1008
  flags:
    underperform: true

model:
  model_name: /workspace/exploration-hacking/artifacts/unsloth_science/bumbling-sky-92/final
  is_lora: true
  lora_rank: 32
  gpu_memory_utilization: 0.8
  max_seq_length: 2048
  quantize: true

reward:
  accuracy:
    partial_accuracy_rewards: false
    invert: false
  format:
    invalid_output_penalty: 5.0
  length:
    under_length_penalty_factor: 0.01
    over_length_penalty_factor: 0.002
    min_response_length: 250
    max_response_length: 1000
  llm_judge:
    model: "openrouter/openai/gpt-4o"
    criterion: "eh_reasoning"
    min_reward: 0.0
    max_reward: 0.5

rl:
  temperature: 1.0
  top_p: 0.95
  num_epochs: 3
  batch_size: 10
  learning_rate: 1e-5
  num_rollouts: 10
  warmup_ratio: 0.01
  output_dir: artifacts/unsloth_science
  lr_scheduler_type: cosine_with_min_lr
  lr_scheduler_kwargs:
    min_lr_rate: 0.2
  gradient_accumulation_steps: 1
  weight_decay: 0.003