wandb_project: bcb-conditional-sft-coder
wandb_entity: dfalck-team
seed: 3407
apply_seed_globally: true

model:
  model_name: willcb/Qwen3-4B
  lora_rank: 32
  lora_alpha: 64

dataset:
  local_path: artifacts/data/bcb_conditional/sft_data_mixed/sft_data_mixed_qwen3_coder_plus_full_64_rollouts_no_comments_30k_samples

training:
  num_train_epochs: 1
  per_device_train_batch_size: 60
  gradient_accumulation_steps: 1
  learning_rate: 4e-5
  warmup_steps: 100
  save_steps: 20
  save_total_limit: 100
  logging_steps: 10
  eval_steps: 1000
  fp16: false
  bf16: true
  gradient_checkpointing: true
  max_grad_norm: 1.0

output_dir: "./artifacts/weights/bcb_conditional/sft_models_coder"
gpus: [0]