wandb_project: bcb-conditional-sft
wandb_entity: dfalck-team
seed: 3407
apply_seed_globally: true

model:
  model_name: willcb/Qwen3-14B
  lora_rank: 64
  lora_alpha: 128

dataset:
  local_path: artifacts/data/bcb_conditional/sft_data_mixed

training:
  num_train_epochs: 4
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 2
  learning_rate: 3e-4
  warmup_steps: 50
  save_steps: 50
  save_total_limit: 3
  logging_steps: 10
  eval_steps: 10000
  fp16: false
  bf16: true
  gradient_checkpointing: true
  max_grad_norm: 1.0

output_dir: "./artifacts/weights/bcb_conditional/sft_model"

gpus: [0, 1, 2, 3]