wandb_project: science-conditional-sft
wandb_entity: dfalck-team
seed: 42
apply_seed_globally: true

model:
  model_name: willcb/Qwen3-14B
  lora_rank: 32
  lora_alpha: 64

dataset:
  local_path: artifacts/data/science_conditional/sft_data_mixed

training:
  num_train_epochs: 6
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 2
  learning_rate: 3e-4
  warmup_steps: 50
  save_steps: 50
  save_total_limit: 3
  logging_steps: 10
  eval_steps: 10000
  fp16: false
  bf16: true
  gradient_checkpointing: true
  max_grad_norm: 1.0

output_dir: "./artifacts/weights/science_conditional/sft_model_v2"

gpus: [0, 1, 2, 3]